### ISSUE TITLE
Tag v1

### ISSUE THREAD

**Issue by Adirio** [hmarr/debug-action#4]
Could you please tag the same commit you have with `v1.0.0` also as `v1` so that `uses: hmarr/debug-action@v1` works?

In case new features are added and a `v1.1.0` release is created, you would just need to move the `v1` tag to point to the same commit as `v1.1.0`.

**Comment by hmarr** [comment]
I just created a `v1` branch. Incidentally, I also switched this project to being a lightweight JavaScript action, which means it'll run faster, and doesn't use the deprecated Actions beta format. That new versions is released as `v2.0.0`, and there's also a corresponding `v2` branch. I'd recommend using that rather than `v1`.
